// <auto-generated />
using GeekShopping.ProductsAPI.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductsAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20241213032720_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductsAPI.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("CatergoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("catergory_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description",
                            ImageUrl = "http://www.abc.com.br/image.jpg",
                            Name = "Smartphone",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 5L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description 2",
                            ImageUrl = "http://www.abc.com.br/image2.jpg",
                            Name = "Smartphone 2",
                            Price = 10.36m
                        },
                        new
                        {
                            Id = 6L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description 3",
                            ImageUrl = "http://www.abc.com.br/image3.jpg",
                            Name = "Smartphone 3",
                            Price = 10.36m
                        },
                        new
                        {
                            Id = 7L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description 4",
                            ImageUrl = "http://www.abc.com.br/image4.jpg",
                            Name = "Smartphone 4",
                            Price = 10.36m
                        },
                        new
                        {
                            Id = 8L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description 5",
                            ImageUrl = "http://www.abc.com.br/image5.jpg",
                            Name = "Smartphone 5",
                            Price = 10.36m
                        },
                        new
                        {
                            Id = 9L,
                            CatergoryName = "Smartphone",
                            Description = "Smartphone Description 6",
                            ImageUrl = "http://www.abc.com.br/image6.jpg",
                            Name = "Smartphone 6",
                            Price = 10.36m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
